project:
  type: website
  output-dir: docs

website:
  title: "Draft"
  navbar:
    left:
      - href: index.ipynb
        text: Home

format:
  html:
    code-link: TRUE
    css: css/styles.css
    toc: true
    toc-location: left



